<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="7.2.6" />
    <ProjectReference Include="..\Firmador.ApiClient\Firmador.ApiClient.csproj" />
    <ProjectReference Include="..\Firmador.Core\Firmador.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\docs\*.pdf" Link="docs\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
