namespace Firmador.Cliente
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                components?.Dispose();
                foreach (var recurso in _recursosVisuales) recurso.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            layoutPrincipal = new TableLayoutPanel();
            layoutCabecera = new TableLayoutPanel();
            layoutTitulos = new TableLayoutPanel();
            layoutCertificado = new TableLayoutPanel();
            layoutDatosCertificado = new TableLayoutPanel();
            layoutDocumentos = new TableLayoutPanel();
            layoutSeleccion = new TableLayoutPanel();
            layoutPaginacion = new TableLayoutPanel();
            layoutFirma = new TableLayoutPanel();
            layoutResumenFirma = new TableLayoutPanel();
            panelGrilla = new Panel();
            picAplicacion = new PictureBox();
            picCertificado = new PictureBox();
            lblAplicacion = new Label();
            lblDocumentosTitulo = new Label();
            lblCertificadoTitulo = new Label();
            lblCertificadoSeleccionado = new Label();
            lblCertificadoDetalle = new Label();
            lblCertificadoEstado = new Label();
            lblSeleccion = new Label();
            lblResumenSeleccion = new Label();
            lblResumenCertificado = new Label();
            lblEstadoGrilla = new Label();
            lblPagina = new Label();
            lblTotalDocumentos = new Label();
            btnBuscar = new Button();
            btnFirmarDocumentos = new Button();
            btnSalir = new Button();
            btnSeleccionarCertificado = new Button();
            btnMarcarTodos = new Button();
            btnLimpiarSeleccion = new Button();
            btnPaginaAnterior = new Button();
            btnPaginaSiguiente = new Button();
            dgvDocumentos = new DataGridView();
            colSeleccionar = new DataGridViewCheckBoxColumn();
            colTipoDocumento = new DataGridViewTextBoxColumn();
            colTitulo = new DataGridViewTextBoxColumn();
            colVerPdf = new DataGridViewLinkColumn();
            colVerParticipantes = new DataGridViewLinkColumn();
            toolTip = new ToolTip(components);
            layoutPrincipal.Name = "layoutPrincipal";
            layoutCabecera.Name = "layoutCabecera";
            layoutTitulos.Name = "layoutTitulos";
            layoutCertificado.Name = "layoutCertificado";
            layoutDatosCertificado.Name = "layoutDatosCertificado";
            layoutDocumentos.Name = "layoutDocumentos";
            layoutSeleccion.Name = "layoutSeleccion";
            layoutPaginacion.Name = "layoutPaginacion";
            layoutFirma.Name = "layoutFirma";
            layoutResumenFirma.Name = "layoutResumenFirma";
            panelGrilla.Name = "panelGrilla";
            picAplicacion.Name = "picAplicacion";
            picCertificado.Name = "picCertificado";
            lblAplicacion.Name = "lblAplicacion";
            lblDocumentosTitulo.Name = "lblDocumentosTitulo";
            lblCertificadoTitulo.Name = "lblCertificadoTitulo";
            lblCertificadoSeleccionado.Name = "lblCertificadoSeleccionado";
            lblCertificadoDetalle.Name = "lblCertificadoDetalle";
            lblCertificadoEstado.Name = "lblCertificadoEstado";
            lblSeleccion.Name = "lblSeleccion";
            lblResumenSeleccion.Name = "lblResumenSeleccion";
            lblResumenCertificado.Name = "lblResumenCertificado";
            lblEstadoGrilla.Name = "lblEstadoGrilla";
            lblPagina.Name = "lblPagina";
            lblTotalDocumentos.Name = "lblTotalDocumentos";
            btnBuscar.Name = "btnBuscar";
            btnFirmarDocumentos.Name = "btnFirmarDocumentos";
            btnSalir.Name = "btnSalir";
            btnSeleccionarCertificado.Name = "btnSeleccionarCertificado";
            btnMarcarTodos.Name = "btnMarcarTodos";
            btnLimpiarSeleccion.Name = "btnLimpiarSeleccion";
            btnPaginaAnterior.Name = "btnPaginaAnterior";
            btnPaginaSiguiente.Name = "btnPaginaSiguiente";
            ((System.ComponentModel.ISupportInitialize)dgvDocumentos).BeginInit();
            ((System.ComponentModel.ISupportInitialize)picAplicacion).BeginInit();
            ((System.ComponentModel.ISupportInitialize)picCertificado).BeginInit();
            SuspendLayout();

            layoutPrincipal.Dock = DockStyle.Fill;
            layoutPrincipal.Margin = new Padding(0);
            layoutPrincipal.ColumnCount = 1;
            layoutPrincipal.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutPrincipal.RowCount = 7;
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            layoutPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 76F));
            layoutPrincipal.Controls.Add(layoutCabecera, 0, 0);
            layoutPrincipal.Controls.Add(layoutCertificado, 0, 1);
            layoutPrincipal.Controls.Add(layoutDocumentos, 0, 2);
            layoutPrincipal.Controls.Add(layoutSeleccion, 0, 3);
            layoutPrincipal.Controls.Add(panelGrilla, 0, 4);
            layoutPrincipal.Controls.Add(layoutPaginacion, 0, 5);
            layoutPrincipal.Controls.Add(layoutFirma, 0, 6);

            layoutCabecera.Dock = DockStyle.Fill;
            layoutCabecera.Margin = new Padding(0);
            layoutCabecera.Padding = new Padding(24, 8, 24, 8);
            layoutCabecera.ColumnCount = 3;
            layoutCabecera.RowCount = 1;
            layoutCabecera.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
            layoutCabecera.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutCabecera.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 92F));
            layoutCabecera.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutCabecera.Controls.Add(picAplicacion, 0, 0);
            layoutCabecera.Controls.Add(layoutTitulos, 1, 0);
            layoutCabecera.Controls.Add(btnSalir, 2, 0);
            picAplicacion.Dock = DockStyle.Fill;
            picAplicacion.SizeMode = PictureBoxSizeMode.CenterImage;
            picAplicacion.TabStop = false;
            layoutTitulos.Dock = DockStyle.Fill;
            layoutTitulos.Margin = new Padding(8, 0, 0, 0);
            layoutTitulos.ColumnCount = 1;
            layoutTitulos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutTitulos.RowCount = 1;
            layoutTitulos.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutTitulos.Controls.Add(lblAplicacion, 0, 0);
            lblAplicacion.Dock = DockStyle.Fill;
            lblAplicacion.Text = "Firmador EDA";
            lblAplicacion.TextAlign = ContentAlignment.MiddleLeft;
            btnSalir.Anchor = AnchorStyles.Right;
            btnSalir.Size = new Size(88, 32);
            btnSalir.Text = "Salir";
            btnSalir.Click += btnSalir_Click;

            layoutCertificado.Dock = DockStyle.Fill;
            layoutCertificado.Margin = new Padding(0);
            layoutCertificado.Padding = new Padding(24, 6, 24, 6);
            layoutCertificado.ColumnCount = 4;
            layoutCertificado.RowCount = 1;
            layoutCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
            layoutCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 194F));
            layoutCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 206F));
            layoutCertificado.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutCertificado.Controls.Add(picCertificado, 0, 0);
            layoutCertificado.Controls.Add(layoutDatosCertificado, 1, 0);
            layoutCertificado.Controls.Add(lblCertificadoEstado, 2, 0);
            layoutCertificado.Controls.Add(btnSeleccionarCertificado, 3, 0);
            picCertificado.Dock = DockStyle.Fill;
            picCertificado.SizeMode = PictureBoxSizeMode.CenterImage;
            picCertificado.TabStop = false;
            layoutDatosCertificado.Dock = DockStyle.Fill;
            layoutDatosCertificado.Margin = new Padding(8, 0, 12, 0);
            layoutDatosCertificado.ColumnCount = 2;
            layoutDatosCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
            layoutDatosCertificado.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutDatosCertificado.RowCount = 2;
            layoutDatosCertificado.RowStyles.Add(new RowStyle(SizeType.Percent, 60F));
            layoutDatosCertificado.RowStyles.Add(new RowStyle(SizeType.Percent, 40F));
            layoutDatosCertificado.Controls.Add(lblCertificadoTitulo, 0, 0);
            layoutDatosCertificado.Controls.Add(lblCertificadoSeleccionado, 1, 0);
            layoutDatosCertificado.Controls.Add(lblCertificadoDetalle, 0, 1);
            layoutDatosCertificado.SetColumnSpan(lblCertificadoDetalle, 2);
            lblCertificadoTitulo.Dock = DockStyle.Fill;
            lblCertificadoTitulo.Margin = new Padding(0);
            lblCertificadoTitulo.TextAlign = ContentAlignment.MiddleLeft;
            lblCertificadoTitulo.Text = "Certificado de firma";
            lblCertificadoSeleccionado.Dock = DockStyle.Fill;
            lblCertificadoSeleccionado.Margin = new Padding(0);
            lblCertificadoSeleccionado.TextAlign = ContentAlignment.MiddleLeft;
            lblCertificadoSeleccionado.Text = "Sin certificado seleccionado";
            lblCertificadoSeleccionado.AutoEllipsis = true;
            lblCertificadoDetalle.Dock = DockStyle.Fill;
            lblCertificadoDetalle.Margin = new Padding(0);
            lblCertificadoDetalle.TextAlign = ContentAlignment.MiddleLeft;
            lblCertificadoDetalle.AutoEllipsis = true;
            lblCertificadoEstado.Dock = DockStyle.Fill;
            lblCertificadoEstado.TextAlign = ContentAlignment.MiddleLeft;
            btnSeleccionarCertificado.Anchor = AnchorStyles.Right;
            btnSeleccionarCertificado.Size = new Size(200, 36);
            btnSeleccionarCertificado.Text = "Seleccionar certificado";
            btnSeleccionarCertificado.Click += btnSeleccionarCertificado_Click;

            layoutDocumentos.Dock = DockStyle.Fill;
            layoutDocumentos.Margin = new Padding(0);
            layoutDocumentos.Padding = new Padding(24, 3, 24, 3);
            layoutDocumentos.ColumnCount = 2;
            layoutDocumentos.RowCount = 1;
            layoutDocumentos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutDocumentos.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
            layoutDocumentos.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutDocumentos.Controls.Add(lblDocumentosTitulo, 0, 0);
            layoutDocumentos.Controls.Add(btnBuscar, 1, 0);
            lblDocumentosTitulo.Dock = DockStyle.Fill;
            lblDocumentosTitulo.Text = "Documentos pendientes";
            lblDocumentosTitulo.TextAlign = ContentAlignment.MiddleLeft;
            btnBuscar.Anchor = AnchorStyles.Right;
            btnBuscar.Size = new Size(120, 36);
            btnBuscar.Text = "Buscar";
            btnBuscar.Click += btnBuscar_Click;

            layoutSeleccion.Dock = DockStyle.Fill;
            layoutSeleccion.Margin = new Padding(0);
            layoutSeleccion.Padding = new Padding(24, 0, 24, 0);
            layoutSeleccion.ColumnCount = 3;
            layoutSeleccion.RowCount = 1;
            layoutSeleccion.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
            layoutSeleccion.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 136F));
            layoutSeleccion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutSeleccion.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutSeleccion.Controls.Add(btnMarcarTodos, 0, 0);
            layoutSeleccion.Controls.Add(btnLimpiarSeleccion, 1, 0);
            layoutSeleccion.Controls.Add(lblSeleccion, 2, 0);
            btnMarcarTodos.Dock = DockStyle.Fill;
            btnMarcarTodos.Text = "Marcar todos";
            btnMarcarTodos.Click += btnMarcarTodos_Click;
            btnLimpiarSeleccion.Dock = DockStyle.Fill;
            btnLimpiarSeleccion.Text = "Limpiar selección";
            btnLimpiarSeleccion.TabIndex = 1;
            btnLimpiarSeleccion.Click += btnLimpiarSeleccion_Click;
            lblSeleccion.Dock = DockStyle.Fill;
            lblSeleccion.Text = "0 seleccionados";
            lblSeleccion.TextAlign = ContentAlignment.MiddleRight;

            panelGrilla.Dock = DockStyle.Fill;
            panelGrilla.Margin = new Padding(24, 0, 24, 0);
            panelGrilla.Padding = new Padding(1);
            panelGrilla.Controls.Add(lblEstadoGrilla);
            panelGrilla.Controls.Add(dgvDocumentos);
            lblEstadoGrilla.Dock = DockStyle.Fill;
            lblEstadoGrilla.TextAlign = ContentAlignment.MiddleCenter;
            lblEstadoGrilla.Text = "Buscá los documentos pendientes de firma";
            dgvDocumentos.Dock = DockStyle.Fill;
            dgvDocumentos.Name = "dgvDocumentos";
            dgvDocumentos.AllowUserToAddRows = false;
            dgvDocumentos.AllowUserToDeleteRows = false;
            dgvDocumentos.AllowUserToResizeRows = false;
            dgvDocumentos.AutoGenerateColumns = false;
            dgvDocumentos.RowHeadersVisible = false;
            dgvDocumentos.MultiSelect = false;
            dgvDocumentos.SelectionMode = DataGridViewSelectionMode.CellSelect;
            dgvDocumentos.Columns.AddRange(new DataGridViewColumn[] { colSeleccionar, colTipoDocumento, colTitulo, colVerPdf, colVerParticipantes });
            dgvDocumentos.CellContentClick += dgvDocumentos_CellContentClick;
            dgvDocumentos.CurrentCellDirtyStateChanged += dgvDocumentos_CurrentCellDirtyStateChanged;
            dgvDocumentos.CellValueChanged += dgvDocumentos_CellValueChanged;
            dgvDocumentos.CellFormatting += dgvDocumentos_CellFormatting;
            dgvDocumentos.CellPainting += dgvDocumentos_CellPainting;
            colSeleccionar.Name = "colSeleccionar";
            colSeleccionar.HeaderText = "";
            colSeleccionar.Width = 44;
            colSeleccionar.Resizable = DataGridViewTriState.False;
            colSeleccionar.SortMode = DataGridViewColumnSortMode.NotSortable;
            colTipoDocumento.Name = "colTipoDocumento";
            colTipoDocumento.HeaderText = "Tipo de documento";
            colTipoDocumento.Width = 210;
            colTipoDocumento.MinimumWidth = 160;
            colTipoDocumento.ReadOnly = true;
            colTipoDocumento.SortMode = DataGridViewColumnSortMode.NotSortable;
            colTitulo.Name = "colTitulo";
            colTitulo.HeaderText = "Título";
            colTitulo.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            colTitulo.MinimumWidth = 220;
            colTitulo.ReadOnly = true;
            colTitulo.SortMode = DataGridViewColumnSortMode.NotSortable;
            colVerPdf.Name = "colVerPdf";
            colVerPdf.HeaderText = "Documento";
            colVerPdf.Text = "Ver PDF";
            colVerPdf.UseColumnTextForLinkValue = true;
            colVerPdf.Width = 120;
            colVerPdf.ReadOnly = true;
            colVerPdf.SortMode = DataGridViewColumnSortMode.NotSortable;
            colVerParticipantes.Name = "colVerParticipantes";
            colVerParticipantes.HeaderText = "Intervinientes";
            colVerParticipantes.Text = "Ver";
            colVerParticipantes.UseColumnTextForLinkValue = true;
            colVerParticipantes.Width = 130;
            colVerParticipantes.ReadOnly = true;
            colVerParticipantes.SortMode = DataGridViewColumnSortMode.NotSortable;

            layoutPaginacion.Dock = DockStyle.Fill;
            layoutPaginacion.Margin = new Padding(0);
            layoutPaginacion.Padding = new Padding(24, 4, 24, 4);
            layoutPaginacion.ColumnCount = 4;
            layoutPaginacion.RowCount = 1;
            layoutPaginacion.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutPaginacion.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42F));
            layoutPaginacion.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 156F));
            layoutPaginacion.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42F));
            layoutPaginacion.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutPaginacion.Controls.Add(lblTotalDocumentos, 0, 0);
            layoutPaginacion.Controls.Add(btnPaginaAnterior, 1, 0);
            layoutPaginacion.Controls.Add(lblPagina, 2, 0);
            layoutPaginacion.Controls.Add(btnPaginaSiguiente, 3, 0);
            lblTotalDocumentos.Dock = DockStyle.Fill;
            lblTotalDocumentos.TextAlign = ContentAlignment.MiddleLeft;
            lblTotalDocumentos.AutoEllipsis = true;
            lblPagina.Dock = DockStyle.Fill;
            lblPagina.TextAlign = ContentAlignment.MiddleCenter;
            btnPaginaAnterior.Dock = DockStyle.Fill;
            btnPaginaAnterior.AccessibleName = "Página anterior";
            btnPaginaAnterior.Click += btnPaginaAnterior_Click;
            btnPaginaSiguiente.Dock = DockStyle.Fill;
            btnPaginaSiguiente.AccessibleName = "Página siguiente";
            btnPaginaSiguiente.TabIndex = 1;
            btnPaginaSiguiente.Click += btnPaginaSiguiente_Click;

            layoutFirma.Dock = DockStyle.Fill;
            layoutFirma.Margin = new Padding(0);
            layoutFirma.Padding = new Padding(24, 12, 24, 12);
            layoutFirma.ColumnCount = 2;
            layoutFirma.RowCount = 1;
            layoutFirma.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutFirma.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 256F));
            layoutFirma.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutFirma.Controls.Add(layoutResumenFirma, 0, 0);
            layoutFirma.Controls.Add(btnFirmarDocumentos, 1, 0);
            layoutResumenFirma.Dock = DockStyle.Fill;
            layoutResumenFirma.Margin = new Padding(0, 0, 12, 0);
            layoutResumenFirma.ColumnCount = 1;
            layoutResumenFirma.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            layoutResumenFirma.RowCount = 2;
            layoutResumenFirma.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            layoutResumenFirma.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            layoutResumenFirma.Controls.Add(lblResumenSeleccion, 0, 0);
            layoutResumenFirma.Controls.Add(lblResumenCertificado, 0, 1);
            lblResumenSeleccion.Dock = DockStyle.Fill;
            lblResumenSeleccion.Text = "Sin documentos seleccionados";
            lblResumenSeleccion.TextAlign = ContentAlignment.MiddleLeft;
            lblResumenCertificado.Dock = DockStyle.Fill;
            lblResumenCertificado.AutoEllipsis = true;
            lblResumenCertificado.TextAlign = ContentAlignment.MiddleLeft;
            btnFirmarDocumentos.Anchor = AnchorStyles.Right;
            btnFirmarDocumentos.Size = new Size(250, 48);
            btnFirmarDocumentos.Text = "Firmar documentos";
            btnFirmarDocumentos.Click += btnFirmarDocumentos_Click;

            layoutCabecera.TabIndex = 0;
            layoutCertificado.TabIndex = 1;
            layoutDocumentos.TabIndex = 2;
            layoutSeleccion.TabIndex = 3;
            panelGrilla.TabIndex = 4;
            layoutPaginacion.TabIndex = 5;
            layoutFirma.TabIndex = 6;
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1180, 760);
            MinimumSize = new Size(940, 650);
            StartPosition = FormStartPosition.CenterScreen;
            Controls.Add(layoutPrincipal);
            Name = "MainForm";
            Text = "Firmador Cliente EDA";
            ((System.ComponentModel.ISupportInitialize)dgvDocumentos).EndInit();
            ((System.ComponentModel.ISupportInitialize)picAplicacion).EndInit();
            ((System.ComponentModel.ISupportInitialize)picCertificado).EndInit();
            ResumeLayout(false);
        }
        #endregion

        private TableLayoutPanel layoutPrincipal;
        private TableLayoutPanel layoutCabecera;
        private TableLayoutPanel layoutTitulos;
        private TableLayoutPanel layoutCertificado;
        private TableLayoutPanel layoutDatosCertificado;
        private TableLayoutPanel layoutDocumentos;
        private TableLayoutPanel layoutSeleccion;
        private TableLayoutPanel layoutPaginacion;
        private TableLayoutPanel layoutFirma;
        private TableLayoutPanel layoutResumenFirma;
        private Panel panelGrilla;
        private PictureBox picAplicacion;
        private PictureBox picCertificado;
        private Label lblAplicacion;
        private Label lblDocumentosTitulo;
        private Label lblCertificadoDetalle;
        private Label lblCertificadoEstado;
        private Label lblSeleccion;
        private Label lblResumenSeleccion;
        private Label lblResumenCertificado;
        private Label lblEstadoGrilla;
        private ToolTip toolTip;
        private Button btnBuscar;
        private Button btnFirmarDocumentos;
        private Button btnSalir;
        private DataGridView dgvDocumentos;
        private DataGridViewCheckBoxColumn colSeleccionar;
        private DataGridViewTextBoxColumn colTipoDocumento;
        private DataGridViewTextBoxColumn colTitulo;
        private DataGridViewLinkColumn colVerPdf;
        private DataGridViewLinkColumn colVerParticipantes;
        private Button btnPaginaAnterior;
        private Button btnPaginaSiguiente;
        private Label lblPagina;
        private Label lblTotalDocumentos;
        private Label lblCertificadoTitulo;
        private Label lblCertificadoSeleccionado;
        private Button btnSeleccionarCertificado;
        private Button btnMarcarTodos;
        private Button btnLimpiarSeleccion;
    }
}
